### ISSUE TITLE
建议创建QQ频道

### ISSUE THREAD

**Issue by bro-sin** [CS-BAOYAN/CSSummerCamp2023#4]
在[绿群首页](https://github.com/CS-BAOYAN#%E5%85%B3%E4%BA%8Eqq%E7%BE%A4%E7%9A%84%E7%AE%A1%E7%90%86)中提到了QQ群管理方面存在着不能满足入群需求、长期接近满员、升级费用高等问题。
对于基数如此大的非商业用交流群体，我认为尝试使用QQ频道这个平台可能会更好：
* 它的人数上限是10万（但需要完成任务逐步解锁人数上限）；
* 同时频道可以区分不同板块以及子频道，比单一QQ群中大家以时间顺序的讨论更利于大家针对某一话题讨论；
* 频道的加入和踢人等维护成本与QQ群差不多；
* 不需要专门为频道人数升级付费；
* 可以只维护一个频道就供所有人讨论交流，相比于维护2-3个群而言，沟通更畅通，信息更连贯，没有那种割裂感。

**Comment by cocoshe** [comment]
个人观点，一方面，频道匿名性会导致信息可信度下降（例如我校频道bbs一些"快递/外卖代取"、”失物招领“等子频道，都是需要绑定学号，防止出事情找不到人追责）；另一方面，频道的消息搜索功能是真的垃圾。（当然第一点应该是大家最在意的）

**Comment by yfyeung** [comment]
感谢建议，我们会考量qq频道的成熟性和可行性，2023年暂时保持qq群的形式进行组织管理

**Comment by Liu-Steve** [comment]
有没有可能创建一个Telegram群组与对应频道，免费，可以容纳的人数比QQ更多，同时Telegram频道也可以接受投稿发布这些挂在Github上的重要信息。

（相信大家既然有办法上Github应该也有办法上tg吧

**Comment by bro-sin** [comment]
> 有没有可能创建一个Telegram群组与对应频道，免费，可以容纳的人数比QQ更多，同时Telegram频道也可以接受投稿发布这些挂在Github上的重要信息。
> 
> （相信大家既然有办法上Github应该也有办法上tg吧

GitHub还是可以直连的，tg可不能

**Comment by bro-sin** [comment]
> 

这个问题应该没多大影响，QQ群也不是实名的啊，信息可信度如何不都看大家自觉，以及自行验证吗。消息搜索的话那可能没办法，得靠人工置顶之类的了，不过一般来说，更加重要的消息应该会在GitHub上吧

**Comment by cocoshe** [comment]
> > 
> 
> 这个问题应该没多大影响，QQ群也不是实名的啊，信息可信度如何不都看大家自觉，以及自行验证吗。消息搜索的话那可能没办法，得靠人工置顶之类的了，不过一般来说，更加重要的消息应该会在GitHub上吧

嗯所以是个人观点，频道甚至改个昵称和头像就行，而QQ群是有用户qq号的，个人认为匿名成本是不对等的

**Comment by yfyeung** [comment]
> 有没有可能创建一个Telegram群组与对应频道，免费，可以容纳的人数比QQ更多，同时Telegram频道也可以接受投稿发布这些挂在Github上的重要信息。
> 
> （相信大家既然有办法上Github应该也有办法上tg吧

感谢建议，tg的话在国内宣传会存在一定的问题，比如在知乎上挂tg的link会被系统删帖，b站直播挂tg的link可能直播间会被封。所以短期来看不是一个好的方式
