### ISSUE TITLE
是否可以在各院截止时间之外再添加一个夏令营实际时间

### ISSUE THREAD

**Issue by i-Yirannn** [CS-BAOYAN/CSSummerCamp2023#49]
这两天在群里看到大家有比较关心哪些夏令营会冲突，我想是不是可以把目前已经确定时间的夏令营直接在对应的条目后面标注？

如果需要，我也可以帮助完成相关工作

**Comment by chenyangzhu1** [comment]
同求

**Comment by Liu-Steve** [comment]
感觉合理，看看管理员学长怎么说，我倒是不嫌麻烦

**Comment by 20xzh02** [comment]
资瓷

**Comment by trace1729** [comment]
支持

**Comment by YushunXiang** [comment]
支持，跪谢

**Comment by yfyeung** [comment]
行 统一一下格式吧
【报名截止：2023.6.15】[电子信息与电气工程学院 计算机科学与工程系](https://www.seiee.sjtu.edu.cn/yjspy_zsgz_sszs/8154.html) 2023.7.3-2023.7.10

**Comment by yfyeung** [comment]
【报名截止：2023.6.15】[电子信息与电气工程学院 电子工程系](https://www.seiee.sjtu.edu.cn/yjspy_zsgz_sszs/8154.html) 直博 2023.6.30 直硕 2023.7.11

**Comment by asimple1** [comment]
可以尝试这个是否可行  https://github.com/asimple1/BAOYAN-Calendar
