### ISSUE TITLE
建议时间更加具体一些

### ISSUE THREAD

**Issue by 2catycm** [CS-BAOYAN/CSSummerCamp2023#68]
目前“截止时间”只有日期，没有具体时刻。看到这个表的时候，以为都是23:59:59截止，导致好多23:59:00, 12:00,16:00, 17:00截止的夏令营被不小心的同学们（比如我）漏掉了。

**Comment by Liu-Steve** [comment]
我觉得这个想法是好的，不过感觉没那么多夏令营给出了具体时间，具体决定交给 @yfyeung 吧，如果同意的话希望有更多人帮忙多提PR完善一下。

**Comment by yfyeung** [comment]
不建议在截止日期最后一天报名，个人觉得还是按照原来的形式只给出截止日期就行。夏令营的报名窗口期大多数很长，不建议拖到ddl。
